Installing the essential packages:

In [1]:
import pandas as pd
import numpy as np

In [2]:
pip install openpyxl

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\Lenovo\PycharmProjects\pythonProject\The first project\Scripts\python.exe -m pip install --upgrade pip' command.


# A. Data source (upload and clean datasets)
## Data. Loyalty Points

In [3]:
Loyalty_points = pd.read_excel(r'D:\Tài liệu\Case study\Case study (raw data and requirements).xlsx', sheet_name = 'Data. Loyalty Points').copy()
Loyalty_points

Service Group        Point Mechanism Maximum Point Per Trans
0                 supermarket   1 points/1000VND GMV              500 points
1                        data  10 points/1000VND GMV             1000 points
2                         cvs   1 points/1000VND GMV              300 points
3                 marketplace   1 points/1000VND GMV              500 points
4  Coffee chains and Milk tea   1 points/1000VND GMV              500 points
5            Offline Beverage   1 points/1000VND GMV              300 points

We need to modify 'Point Mechanism' and 'Maxium Point Per Trans' to the right data type. 

In [4]:
Loyalty_points['Point Mechanism']=Loyalty_points['Point Mechanism'].str.split().str[0]
Loyalty_points['Point Mechanism']=pd.to_numeric(Loyalty_points['Point Mechanism'])
Loyalty_points

Service Group  Point Mechanism Maximum Point Per Trans
0                 supermarket                1              500 points
1                        data               10             1000 points
2                         cvs                1              300 points
3                 marketplace                1              500 points
4  Coffee chains and Milk tea                1              500 points
5            Offline Beverage                1              300 points

Change the column's name to be shorter:

In [5]:
Loyalty_points.rename(columns={'Maximum Point Per Trans':'Maximum Point'}, inplace = True)

Take only nummeric value of Maximum Point:

In [6]:
Loyalty_points['Maximum Point']=Loyalty_points['Maximum Point'].str.split().str[0]
Loyalty_points['Maximum Point']=pd.to_numeric(Loyalty_points['Maximum Point'])
Loyalty_points

Service Group  Point Mechanism  Maximum Point
0                 supermarket                1            500
1                        data               10           1000
2                         cvs                1            300
3                 marketplace                1            500
4  Coffee chains and Milk tea                1            500
5            Offline Beverage                1            300

## Data. Loyalty Benefits

In [7]:
Loyalty_benefits = pd.read_excel(r'D:\Tài liệu\Case study\Case study (raw data and requirements).xlsx', sheet_name = 'Data. Loyalty benefits').copy()
Loyalty_benefits.rename(columns = {'Group':'Service Group'}, inplace = True)
Loyalty_benefits

Class ID     Service Group  %cashback
0          2               cvs          5
1          2  Offline Beverage          5
2          2              data          5
3          3               cvs          7
4          3  Offline Beverage          7
5          3              data          7
6          3       marketplace          2
7          3       supermarket          2
8          4               cvs         12
9          4  Offline Beverage         12
10         4              data         12
11         4       marketplace          5
12         4       supermarket          5

Format %cashback column to numeric form:

In [8]:
Loyalty_benefits['%cashback'] = pd.to_numeric(Loyalty_benefits['%cashback'])
Loyalty_benefits['%cashback'].dtypes

dtype('int64')

## Data. Transactions
I will upload and create a copy of the dataset so Python does not have to re-import dataset every we run the code line: 

In [9]:
Transactions = pd.read_excel(r'D:\Tài liệu\Case study\Case study (raw data and requirements).xlsx', sheet_name = 'Data. Transactions').copy()
Transactions

DATE     Order_id NEWVERTICAL_Merchant  MerchantID   User_id  \
0     2021-01-01   8733622706          Marketplace          37  61386143   
1     2021-01-01   8726857991          Supermarket           9  48453125   
2     2021-01-01   8737326894          Supermarket           9  49921027   
3     2021-01-01   8732579078          supermarket           9  46022523   
4     2021-01-01   8725567343                  CVS           8  44014594   
...          ...          ...                  ...         ...       ...   
49170 2022-03-31  22531432792              Airtime          41  53272777   
49171 2022-03-31  22516959788              Airtime          41  41605249   
49172 2022-03-31  22518046622              Airtime          30  29029358   
49173 2022-03-31  22518047037              Airtime          30  29029358   
49174 2022-03-31  22528638021              Airtime          43  52354215   

          GMV Service Group  
0      100000   marketplace  
1        5000   supermarket  
2      106600   supermarket  
3      270000   supermarket  
4       68000           cvs  
...       ...           ...  
49170   30000          data  
49171   10000          data  
49172   42000          data  
49173    5000          data  
49174   15000          data  

[49175 rows x 7 columns]

Each transaction will has a unique Id so I will drop the duplicates in Order_id and any rows having missing values across the dataset:

In [10]:
Transactions = pd.DataFrame(Transactions)
Transactions.drop_duplicates(subset = ['Order_id'], inplace= True)
Transactions.dropna(inplace = True)
Transactions

DATE     Order_id NEWVERTICAL_Merchant  MerchantID   User_id  \
0     2021-01-01   8733622706          Marketplace          37  61386143   
1     2021-01-01   8726857991          Supermarket           9  48453125   
2     2021-01-01   8737326894          Supermarket           9  49921027   
3     2021-01-01   8732579078          supermarket           9  46022523   
4     2021-01-01   8725567343                  CVS           8  44014594   
...          ...          ...                  ...         ...       ...   
49170 2022-03-31  22531432792              Airtime          41  53272777   
49171 2022-03-31  22516959788              Airtime          41  41605249   
49172 2022-03-31  22518046622              Airtime          30  29029358   
49173 2022-03-31  22518047037              Airtime          30  29029358   
49174 2022-03-31  22528638021              Airtime          43  52354215   

          GMV Service Group  
0      100000   marketplace  
1        5000   supermarket  
2      106600   supermarket  
3      270000   supermarket  
4       68000           cvs  
...       ...           ...  
49170   30000          data  
49171   10000          data  
49172   42000          data  
49173    5000          data  
49174   15000          data  

[49175 rows x 7 columns]

Format Date column to date form:

In [11]:
Transactions['DATE'] = pd.to_datetime(Transactions['DATE'], format = '%Y-%m-%d')
Transactions['DATE']

0       2021-01-01
1       2021-01-01
2       2021-01-01
3       2021-01-01
4       2021-01-01
           ...    
49170   2022-03-31
49171   2022-03-31
49172   2022-03-31
49173   2022-03-31
49174   2022-03-31
Name: DATE, Length: 49175, dtype: datetime64[ns]

Format GMV column to numeric form:

In [12]:
Transactions['GMV']=pd.to_numeric(Transactions['GMV'])
Transactions['GMV'].dtypes

dtype('int64')

## Data. Merchant

In [13]:
Merchant = pd.read_excel(r'D:\Tài liệu\Case study\Case study (raw data and requirements).xlsx', sheet_name = 'Data.Merchant')
Merchant

Unnamed: 0                    ServiceID               Service Group  \
0           NaN                      7eleven                         cvs   
1           NaN               FBIOQC20191008                         cvs   
2           NaN                      opcaeon                 supermarket   
3           NaN               FBGPCQ20190613                 supermarket   
4           NaN               FBONXG20191120                 supermarket   
..          ...                          ...                         ...   
213         NaN       buycard_data_vinaphone                        data   
214         NaN  gift_buycard_data_vinaphone                        data   
215         NaN              topup_data_vina                        data   
216         NaN                   adamcoffee  Coffee chains and Milk tea   
217         NaN               FBFTUR20190422  Coffee chains and Milk tea   

        Merchant  MerchantID  
0        7eleven           1  
1        7eleven           1  
2      Aeon Mall           2  
3      Aeon Mall           2  
4      Aeon Mall           2  
..           ...         ...  
213    Vinaphone          43  
214    Vinaphone          43  
215    Vinaphone          43  
216  Adam Coffee          44  
217  Adam Coffee          44  

[218 rows x 5 columns]

Drop the blank column:

In [14]:
Merchant.drop(columns = Merchant.columns[0],axis = 1, inplace = True)
Merchant

ServiceID               Service Group     Merchant  \
0                        7eleven                         cvs      7eleven   
1                 FBIOQC20191008                         cvs      7eleven   
2                        opcaeon                 supermarket    Aeon Mall   
3                 FBGPCQ20190613                 supermarket    Aeon Mall   
4                 FBONXG20191120                 supermarket    Aeon Mall   
..                           ...                         ...          ...   
213       buycard_data_vinaphone                        data    Vinaphone   
214  gift_buycard_data_vinaphone                        data    Vinaphone   
215              topup_data_vina                        data    Vinaphone   
216                   adamcoffee  Coffee chains and Milk tea  Adam Coffee   
217               FBFTUR20190422  Coffee chains and Milk tea  Adam Coffee   

     MerchantID  
0             1  
1             1  
2             2  
3             2  
4             2  
..          ...  
213          43  
214          43  
215          43  
216          44  
217          44  

[218 rows x 4 columns]

# B. Requirements
## Part 1. Data Processing
### Question 1:
Combined with the 'Loyalty Points' table, add a column 'Loyalty Points' in 'Transactions' table with given rules. Then create another table named 'Loyalty Ranking' which must includes columns named Rank_name and Calculated_points to calculate the Rank of each user on daily basic. **At the end of Mar 2022, how many user achived rank Gold?**

Important Note: 
- Points calculated for each transaction will be expired after 30 days since the day that transaction is made
- User's rank will be reduced or increased accordingly to the change of their accumulated loyalty points.


First, let's create the table of rules for ranking

In [15]:
Rules_table = {'Class ID':[1,2,3,4],'Rank name':['STANDARD','SILVER','GOLD','DIAMOND'],'Loyalty Points':[1,1000,2000,5000]}
Ranking_rules = pd.DataFrame(Rules_table, columns = ['Class ID','Rank name','Loyalty Points'])
Ranking_rules

Class ID Rank name  Loyalty Points
0         1  STANDARD               1
1         2    SILVER            1000
2         3      GOLD            2000
3         4   DIAMOND            5000

Set Loyalty Points to numberic format

In [16]:
Ranking_rules['Loyalty Points']=Ranking_rules['Loyalty Points'].astype(float)
Ranking_rules['Loyalty Points'].dtypes

dtype('float64')

Let's add loyalty Points column to Transactions dataframe so that will be more convenient to later calculations. 
Loyalty Points are obtained depending on GMV and the limited point number. First, I will add two more columns 'Point Mechanism' and 'Maximum Point' with reference to Loyalty_Points table 

In [17]:
Transactions =  pd.merge(Transactions, Loyalty_points, on = 'Service Group', how= 'left')
Transactions

DATE     Order_id NEWVERTICAL_Merchant  MerchantID   User_id  \
0     2021-01-01   8733622706          Marketplace          37  61386143   
1     2021-01-01   8726857991          Supermarket           9  48453125   
2     2021-01-01   8737326894          Supermarket           9  49921027   
3     2021-01-01   8732579078          supermarket           9  46022523   
4     2021-01-01   8725567343                  CVS           8  44014594   
...          ...          ...                  ...         ...       ...   
49170 2022-03-31  22531432792              Airtime          41  53272777   
49171 2022-03-31  22516959788              Airtime          41  41605249   
49172 2022-03-31  22518046622              Airtime          30  29029358   
49173 2022-03-31  22518047037              Airtime          30  29029358   
49174 2022-03-31  22528638021              Airtime          43  52354215   

          GMV Service Group  Point Mechanism  Maximum Point  
0      100000   marketplace                1            500  
1        5000   supermarket                1            500  
2      106600   supermarket                1            500  
3      270000   supermarket                1            500  
4       68000           cvs                1            300  
...       ...           ...              ...            ...  
49170   30000          data               10           1000  
49171   10000          data               10           1000  
49172   42000          data               10           1000  
49173    5000          data               10           1000  
49174   15000          data               10           1000  

[49175 rows x 9 columns]

Then add Loyalty Points for each transaction depending on GMV while ensuring the Loyalty Points are not higher than that Maximum Point

In [18]:
Transactions['Expected Loyalty Points'] = np.floor(Transactions['GMV']/1000)*(Transactions['Point Mechanism'])
Transactions

DATE     Order_id NEWVERTICAL_Merchant  MerchantID   User_id  \
0     2021-01-01   8733622706          Marketplace          37  61386143   
1     2021-01-01   8726857991          Supermarket           9  48453125   
2     2021-01-01   8737326894          Supermarket           9  49921027   
3     2021-01-01   8732579078          supermarket           9  46022523   
4     2021-01-01   8725567343                  CVS           8  44014594   
...          ...          ...                  ...         ...       ...   
49170 2022-03-31  22531432792              Airtime          41  53272777   
49171 2022-03-31  22516959788              Airtime          41  41605249   
49172 2022-03-31  22518046622              Airtime          30  29029358   
49173 2022-03-31  22518047037              Airtime          30  29029358   
49174 2022-03-31  22528638021              Airtime          43  52354215   

          GMV Service Group  Point Mechanism  Maximum Point  \
0      100000   marketplace                1            500   
1        5000   supermarket                1            500   
2      106600   supermarket                1            500   
3      270000   supermarket                1            500   
4       68000           cvs                1            300   
...       ...           ...              ...            ...   
49170   30000          data               10           1000   
49171   10000          data               10           1000   
49172   42000          data               10           1000   
49173    5000          data               10           1000   
49174   15000          data               10           1000   

       Expected Loyalty Points  
0                        100.0  
1                          5.0  
2                        106.0  
3                        270.0  
4                         68.0  
...                        ...  
49170                    300.0  
49171                    100.0  
49172                    420.0  
49173                     50.0  
49174                    150.0  

[49175 rows x 10 columns]

If Expected Loyalty Points is less than Maximum Point, Loyalty Point equals to Expected Loyalty Points, otherwise Maximum Point

In [19]:
Transactions['Loyalty Points'] = np.where(Transactions['Expected Loyalty Points'] <= Transactions['Maximum Point'], Transactions['Expected Loyalty Points'], Transactions['Maximum Point'])
Transactions.drop(['Expected Loyalty Points'], axis = 1, inplace = True)
Transactions

DATE     Order_id NEWVERTICAL_Merchant  MerchantID   User_id  \
0     2021-01-01   8733622706          Marketplace          37  61386143   
1     2021-01-01   8726857991          Supermarket           9  48453125   
2     2021-01-01   8737326894          Supermarket           9  49921027   
3     2021-01-01   8732579078          supermarket           9  46022523   
4     2021-01-01   8725567343                  CVS           8  44014594   
...          ...          ...                  ...         ...       ...   
49170 2022-03-31  22531432792              Airtime          41  53272777   
49171 2022-03-31  22516959788              Airtime          41  41605249   
49172 2022-03-31  22518046622              Airtime          30  29029358   
49173 2022-03-31  22518047037              Airtime          30  29029358   
49174 2022-03-31  22528638021              Airtime          43  52354215   

          GMV Service Group  Point Mechanism  Maximum Point  Loyalty Points  
0      100000   marketplace                1            500           100.0  
1        5000   supermarket                1            500             5.0  
2      106600   supermarket                1            500           106.0  
3      270000   supermarket                1            500           270.0  
4       68000           cvs                1            300            68.0  
...       ...           ...              ...            ...             ...  
49170   30000          data               10           1000           300.0  
49171   10000          data               10           1000           100.0  
49172   42000          data               10           1000           420.0  
49173    5000          data               10           1000            50.0  
49174   15000          data               10           1000           150.0  

[49175 rows x 10 columns]

I will filter all the transactions that have the Loyalty Point available to Mar 31st, 2022. Remember that Points calculated for each transaction will be expired after 30 days since the day that transaction is made, this means the furthest transaction date was Mar 2nd, 2022.

In [20]:
Transactions_filter_1 = Transactions[Transactions['DATE'] >= '2022-03-02']
Transactions_filter_1 

DATE     Order_id NEWVERTICAL_Merchant  MerchantID   User_id  \
42637 2022-03-02  21549087636          Supermarket          25  45715492   
42638 2022-03-02  21558157954          Supermarket          25  44080459   
42639 2022-03-02  21545970988          Supermarket          25  37381541   
42640 2022-03-02  21557916934          Supermarket          25  44080459   
42641 2022-03-02  21562502367                  CVS          28  47025182   
...          ...          ...                  ...         ...       ...   
49170 2022-03-31  22531432792              Airtime          41  53272777   
49171 2022-03-31  22516959788              Airtime          41  41605249   
49172 2022-03-31  22518046622              Airtime          30  29029358   
49173 2022-03-31  22518047037              Airtime          30  29029358   
49174 2022-03-31  22528638021              Airtime          43  52354215   

          GMV Service Group  Point Mechanism  Maximum Point  Loyalty Points  
42637   55000   supermarket                1            500            55.0  
42638  203600   supermarket                1            500           203.0  
42639  526400   supermarket                1            500           500.0  
42640   25000   supermarket                1            500            25.0  
42641   36000           cvs                1            300            36.0  
...       ...           ...              ...            ...             ...  
49170   30000          data               10           1000           300.0  
49171   10000          data               10           1000           100.0  
49172   42000          data               10           1000           420.0  
49173    5000          data               10           1000            50.0  
49174   15000          data               10           1000           150.0  

[6538 rows x 10 columns]

To find the ranking of each user, I sum the Loyalty Points by users

In [21]:
Users_point = Transactions_filter_1.groupby(Transactions_filter_1['User_id'])['Loyalty Points'].sum().reset_index()
Users_point = pd.DataFrame(Users_point,columns = ['User_id','Loyalty Points']).sort_values('Loyalty Points')
Users_point

User_id  Loyalty Points
1198  46676078             1.0
1413  49914210             1.0
710   40481625             1.0
1727  55415779             1.0
261   26542291             1.0
...        ...             ...
1497  51432947          8131.0
1391  49689927          9100.0
1432  50185392         15545.0
1267  47662326         20039.0
1701  54960619         21300.0

[1921 rows x 2 columns]

Merge Users_point and Ranking_rules by Loyalty Points to have the rank name of each user

In [22]:
Users_point = pd.merge_asof(Users_point, Ranking_rules, on = 'Loyalty Points')
Users_point

User_id  Loyalty Points  Class ID Rank name
0     46676078             1.0         1  STANDARD
1     49914210             1.0         1  STANDARD
2     40481625             1.0         1  STANDARD
3     55415779             1.0         1  STANDARD
4     26542291             1.0         1  STANDARD
...        ...             ...       ...       ...
1916  51432947          8131.0         4   DIAMOND
1917  49689927          9100.0         4   DIAMOND
1918  50185392         15545.0         4   DIAMOND
1919  47662326         20039.0         4   DIAMOND
1920  54960619         21300.0         4   DIAMOND

[1921 rows x 4 columns]

Number of GOLD users

In [23]:
len(Users_point[Users_point['Rank name'] == 'GOLD'])

61

**At the end of Mar 2022, there were 61 users achiving rank Gold**

### Question 2:
Combined with the 'Loyalty benefits' table and 'Loyalty Ranking' table, add columns '%cashback'  in 'Transactions' table and **calculate the total cashback cost in Feb 2022.** 


Cashback cost is calculated from this equation: <br>
Cashback cost = GMV * %cashback <br>
From Transactions dataset, we already have the GMV, then we have to find the responding %cashback.
From Loyalty Benefits datset, %cashback depends on the rank name and the service. We've got the service information, so we need to find the rank for the user that did the transactions. The user rank is determined by the Loyalty Points that users have earned in the last 30 days. Therefore, the furthest date that is used to calculated is Jan 3rd, 2022.

Let's create a dataframe for transactions in Feb 2022

In [24]:
filter1 = '2022-02-01' <= Transactions['DATE']
filter2 = Transactions['DATE'] <= '2022-02-28'
Feb_transactions = Transactions[filter1 & filter2]
Feb_transactions

DATE     Order_id NEWVERTICAL_Merchant  MerchantID   User_id  \
36987 2022-02-01  20510379115              Airtime          30  32983630   
36988 2022-02-01  20514342785              Airtime          30   3560552   
36989 2022-02-01  20502357355              Airtime          30  52261329   
36990 2022-02-01  20514894447              Airtime          30  45221505   
36991 2022-02-01  20498110250              Airtime          30  32983630   
...          ...          ...                  ...         ...       ...   
42461 2022-02-28  21470152866              Airtime          41  47836168   
42462 2022-02-28  21480593166              Airtime          41  48347141   
42463 2022-02-28  21493381211              Airtime          41  60420174   
42464 2022-02-28  21481080145              Airtime          30  17938338   
42465 2022-02-28  21483730684              Airtime          43  52354215   

         GMV Service Group  Point Mechanism  Maximum Point  Loyalty Points  
36987  14000          data               10           1000           140.0  
36988  10000          data               10           1000           100.0  
36989  28000          data               10           1000           280.0  
36990  20000          data               10           1000           200.0  
36991   5000          data               10           1000            50.0  
...      ...           ...              ...            ...             ...  
42461  15000          data               10           1000           150.0  
42462  15000          data               10           1000           150.0  
42463  25000          data               10           1000           250.0  
42464  10000          data               10           1000           100.0  
42465  15000          data               10           1000           150.0  

[5479 rows x 10 columns]

Let's have a look again at Transactions:

In [25]:
Transactions

DATE     Order_id NEWVERTICAL_Merchant  MerchantID   User_id  \
0     2021-01-01   8733622706          Marketplace          37  61386143   
1     2021-01-01   8726857991          Supermarket           9  48453125   
2     2021-01-01   8737326894          Supermarket           9  49921027   
3     2021-01-01   8732579078          supermarket           9  46022523   
4     2021-01-01   8725567343                  CVS           8  44014594   
...          ...          ...                  ...         ...       ...   
49170 2022-03-31  22531432792              Airtime          41  53272777   
49171 2022-03-31  22516959788              Airtime          41  41605249   
49172 2022-03-31  22518046622              Airtime          30  29029358   
49173 2022-03-31  22518047037              Airtime          30  29029358   
49174 2022-03-31  22528638021              Airtime          43  52354215   

          GMV Service Group  Point Mechanism  Maximum Point  Loyalty Points  
0      100000   marketplace                1            500           100.0  
1        5000   supermarket                1            500             5.0  
2      106600   supermarket                1            500           106.0  
3      270000   supermarket                1            500           270.0  
4       68000           cvs                1            300            68.0  
...       ...           ...              ...            ...             ...  
49170   30000          data               10           1000           300.0  
49171   10000          data               10           1000           100.0  
49172   42000          data               10           1000           420.0  
49173    5000          data               10           1000            50.0  
49174   15000          data               10           1000           150.0  

[49175 rows x 10 columns]

We all know that money is cashbacked for the user after they do the transaction. Also the cashback% is depend on the rank of the user and the rank depends on the loyalty points of the user **before** the transaction. However, in case there were more than one transaction happening in a day from one user, we do not know which transactions is before or after which transactions because there was no information of exact time(hour, minute, second) of the transactions. Therefore, let's assume the rank of the user will be determined on the loyalty point that the user had earned at the end of the day before the transaction. <br>
From Feb_transactions table, for each date, I will filter from the Transactions the dataset including all the transaction happen in the last 30 days and assign it with name 'reference'. The reason I do not put the following code lines available because I will put all of them under a function and take date and user as parameters. Remember our assumption? the code will be like this:

**filter3 = Transactions['DATE'] < Feb_transactions['DATE']
filter4 = Transactions[Feb_transactions['DATE'] - 30 <= Transactions['DATE']
reference_30days = Transactions[filter3 & filter4]<br>**
Next, we need to check if a user did any transaction in the last 30 days before they have been on the list of users who have transactions in Feb. If they did, I will assign all their transactions infor with name 'points' <br>
**point_calculating = reference_30days[reference_30days['User_id'] = user))<br>**
Finally, we sum all the Loyalty Points from 'points' and start over with the next date in Feb_transactions.This is the code <br>
**accumulated_points = sum(point['Loyalty Points'])** <br>
The function to calculate accumulated points for the users making money transations in Feb

In [26]:
from datetime import timedelta

In [27]:
def points_calculating(date, user):
    filter3 = date - timedelta(days=30) <= Transactions['DATE']
    filter4 = Transactions['DATE'] < date
    reference_30days = Transactions[filter3 & filter4]
    point_calculating = reference_30days[reference_30days['User_id'] == user]
    accumulated_points = sum(point_calculating['Loyalty Points'])
    return accumulated_points

I will extract DATE and User_id columns from Feb_transactions dataset. 

In [28]:
Accumulated_points = Feb_transactions.loc[:,['DATE','User_id','GMV','Service Group']]
Accumulated_points

DATE   User_id    GMV Service Group
36987 2022-02-01  32983630  14000          data
36988 2022-02-01   3560552  10000          data
36989 2022-02-01  52261329  28000          data
36990 2022-02-01  45221505  20000          data
36991 2022-02-01  32983630   5000          data
...          ...       ...    ...           ...
42461 2022-02-28  47836168  15000          data
42462 2022-02-28  48347141  15000          data
42463 2022-02-28  60420174  25000          data
42464 2022-02-28  17938338  10000          data
42465 2022-02-28  52354215  15000          data

[5479 rows x 4 columns]

Now pass each row of the Date_user to the function and save the results to the Loyalty Points column :

In [29]:
Accumulated_points['Loyalty Points'] = Accumulated_points.apply(lambda row: points_calculating(row['DATE'], row['User_id']), axis = 1)
Accumulated_points

DATE   User_id    GMV Service Group  Loyalty Points
36987 2022-02-01  32983630  14000          data           400.0
36988 2022-02-01   3560552  10000          data          1464.0
36989 2022-02-01  52261329  28000          data           200.0
36990 2022-02-01  45221505  20000          data            50.0
36991 2022-02-01  32983630   5000          data           400.0
...          ...       ...    ...           ...             ...
42461 2022-02-28  47836168  15000          data          3050.0
42462 2022-02-28  48347141  15000          data             0.0
42463 2022-02-28  60420174  25000          data           720.0
42464 2022-02-28  17938338  10000          data             0.0
42465 2022-02-28  52354215  15000          data            80.0

[5479 rows x 5 columns]

Let's merge this with Ranking_rules to determine the ranking of the users for each transactions: 

In [30]:
Ranking_name = pd.merge_asof(Accumulated_points.sort_values('Loyalty Points'),Ranking_rules.loc[:,['Class ID','Loyalty Points']], on = 'Loyalty Points')
Ranking_name

DATE   User_id     GMV Service Group  Loyalty Points  Class ID
0    2022-02-15  39097762   10000          data             0.0       NaN
1    2022-02-15  60197163   58200   marketplace             0.0       NaN
2    2022-02-19  46435634   15000          data             0.0       NaN
3    2022-02-08  48441410    7000          data             0.0       NaN
4    2022-02-15  41365617  183600   marketplace             0.0       NaN
...         ...       ...     ...           ...             ...       ...
5474 2022-02-27  47662326  142400   marketplace         20759.0       4.0
5475 2022-02-27  47662326  161400   marketplace         20759.0       4.0
5476 2022-02-27  47662326  438400   marketplace         20759.0       4.0
5477 2022-02-27  47662326  196400   marketplace         20759.0       4.0
5478 2022-02-28  47662326  332266   marketplace         21932.0       4.0

[5479 rows x 6 columns]

Then merge with Loytalty_benefits to have %cashback 

In [31]:
Cash_back = pd.merge(Ranking_name, Loyalty_benefits, on=['Service Group', 'Class ID'])
Cash_back

DATE   User_id     GMV Service Group  Loyalty Points  Class ID  \
0   2022-02-28  54849847  120000          data          1000.0       2.0   
1   2022-02-12  45962103   14000          data          1000.0       2.0   
2   2022-02-22  28357777   10000          data          1000.0       2.0   
3   2022-02-16  40718009  120000          data          1000.0       2.0   
4   2022-02-05  44634651   20000          data          1000.0       2.0   
..         ...       ...     ...           ...             ...       ...   
974 2022-02-17  55200938  701316   supermarket          7741.0       4.0   
975 2022-02-13  55200938   55500   supermarket          8171.0       4.0   
976 2022-02-21  55200938  314320   supermarket          9306.0       4.0   
977 2022-02-06  50185392  100000   supermarket         12874.0       4.0   
978 2022-02-06  50185392  100000   supermarket         12874.0       4.0   

     %cashback  
0            5  
1            5  
2            5  
3            5  
4            5  
..         ...  
974          5  
975          5  
976          5  
977          5  
978          5  

[979 rows x 7 columns]

Calculate Cachback Cost by multipling GMV with %cashback while limiting Cashback Cost of each Transaction is lower than 10,000

In [32]:
Cash_back['Expected Cost'] = Cash_back['GMV']*Cash_back['%cashback']/100 
Cash_back['Cashback Cost'] = np.where(Cash_back['Expected Cost'] < 10000, Cash_back['Expected Cost'], 10000)
Cash_back.drop(['Expected Cost'], axis = 1, inplace = True)
Cash_back

DATE   User_id     GMV Service Group  Loyalty Points  Class ID  \
0   2022-02-28  54849847  120000          data          1000.0       2.0   
1   2022-02-12  45962103   14000          data          1000.0       2.0   
2   2022-02-22  28357777   10000          data          1000.0       2.0   
3   2022-02-16  40718009  120000          data          1000.0       2.0   
4   2022-02-05  44634651   20000          data          1000.0       2.0   
..         ...       ...     ...           ...             ...       ...   
974 2022-02-17  55200938  701316   supermarket          7741.0       4.0   
975 2022-02-13  55200938   55500   supermarket          8171.0       4.0   
976 2022-02-21  55200938  314320   supermarket          9306.0       4.0   
977 2022-02-06  50185392  100000   supermarket         12874.0       4.0   
978 2022-02-06  50185392  100000   supermarket         12874.0       4.0   

     %cashback  Cashback Cost  
0            5         6000.0  
1            5          700.0  
2            5          500.0  
3            5         6000.0  
4            5         1000.0  
..         ...            ...  
974          5        10000.0  
975          5         2775.0  
976          5        10000.0  
977          5         5000.0  
978          5         5000.0  

[979 rows x 8 columns]

**Total cashback cost in Feb 2022:**

In [33]:
sum(Cash_back['Cashback Cost'])

3009699.94

## Part 3. Extended questions 
### Question 2:

Gamification is usually a sensible option for apps to raise users’ stickiness. In our loyalty program development strategy, we also plan to hold a small game for users. The rule is simple: any users who can maintain a 20-day or longer streak of being in the DIAMOND ranking is a winner (in other words, winners are users who have total loyalty points greater than or equal to 5,000 for at least 20 consecutive days). We also want to give a special reward for the user(s) who can maintain the longest streak. Could you help us to calculate **how many winners were there during the last thirty days in the given data (March 01 - March 31)** and **who was/were the one(s) boasting the longest streak during that time?**

From Mar 1 to Mar 31, to win the game, the winners have to be in rank DIAMOND in 20-day streak. Therefore, Mar 12 is the last day to become DIAMOND. This means that, after this day to the end of the game day, there is not streak can last for longer than 19 days. 
Because of that, let find out which users are the DIAMOND on Mar 12.<br>
Similar to Question 1 Part 1, I will fiter all the transaction happening in 30 days before Mar 12, sum the loyalty points by user_id and find the rank name:

In [34]:
filter5 = Transactions['DATE'] >= '2022-02-12' 
filter6 = Transactions['DATE'] <= '2022-03-11'
Transactions_filter_2 = Transactions[filter5&filter6]
Transactions_filter_2

DATE     Order_id NEWVERTICAL_Merchant  MerchantID   User_id  \
38567 2022-02-12  20960120146     Paid bank cashin           2  50980141   
38568 2022-02-12  20946294225                  CVS          28  44086812   
38569 2022-02-12  20966247280                  CVS          28  42894369   
38570 2022-02-12  20964430309             Paylater          37  38713070   
38571 2022-02-12  20964143690          Marketplace          37  38713070   
...          ...          ...                  ...         ...       ...   
44697 2022-03-11  21835968973              Airtime          41  52602575   
44698 2022-03-11  21805761774              Airtime          41  42116909   
44699 2022-03-11  21854881954              Airtime          41  20904319   
44700 2022-03-11  21836400078              Airtime          30  49224926   
44701 2022-03-11  21825336559              Airtime          43  55491642   

          GMV Service Group  Point Mechanism  Maximum Point  Loyalty Points  
38567   40000   supermarket                1            500            40.0  
38568   52000           cvs                1            300            52.0  
38569   38000           cvs                1            300            38.0  
38570  416723   marketplace                1            500           416.0  
38571  696255   marketplace                1            500           500.0  
...       ...           ...              ...            ...             ...  
44697   10000          data               10           1000           100.0  
44698   10000          data               10           1000           100.0  
44699   10000          data               10           1000           100.0  
44700   10000          data               10           1000           100.0  
44701   15000          data               10           1000           150.0  

[6135 rows x 10 columns]

Sum Loyalty Point by User_id and set the results to dataframe

In [35]:
Users_point_2 = Transactions_filter_2.groupby(Transactions_filter_2['User_id'])['Loyalty Points'].sum().reset_index()
Users_point_2 = pd.DataFrame(Users_point_2,columns = ['User_id','Loyalty Points']).sort_values('Loyalty Points')
Users_point_2

User_id  Loyalty Points
274   29332951             1.0
809   42453684             1.0
222   24707620             1.0
1007  44629265             1.0
1085  45618828             1.0
...        ...             ...
1628  55200938          6088.0
591   39314846          6265.0
1441  51432947          6757.0
1707  57207697          8060.0
1210  47662326         26364.0

[1860 rows x 2 columns]

Find rank name for each user on Mar 12

In [36]:
Users_point_2 = pd.merge_asof(Users_point_2, Ranking_rules, on = 'Loyalty Points')
Users_point_2

User_id  Loyalty Points  Class ID Rank name
0     29332951             1.0         1  STANDARD
1     42453684             1.0         1  STANDARD
2     24707620             1.0         1  STANDARD
3     44629265             1.0         1  STANDARD
4     45618828             1.0         1  STANDARD
...        ...             ...       ...       ...
1855  55200938          6088.0         4   DIAMOND
1856  39314846          6265.0         4   DIAMOND
1857  51432947          6757.0         4   DIAMOND
1858  57207697          8060.0         4   DIAMOND
1859  47662326         26364.0         4   DIAMOND

[1860 rows x 4 columns]

Omit users that are not DIAMOND:

In [37]:
Diamond_users = Users_point_2[Users_point_2['Rank name'] == 'DIAMOND']
Diamond_users

User_id  Loyalty Points  Class ID Rank name
1852  43160536          5082.0         4   DIAMOND
1853  50185392          5306.0         4   DIAMOND
1854  44901759          5774.0         4   DIAMOND
1855  55200938          6088.0         4   DIAMOND
1856  39314846          6265.0         4   DIAMOND
1857  51432947          6757.0         4   DIAMOND
1858  57207697          8060.0         4   DIAMOND
1859  47662326         26364.0         4   DIAMOND

Next, we need to check these users to see their money transactions sreak during Mar. Similarly to the Question 2 in Part 1, we will create a function take date and user_id as parameters because we need to have rank name of users in Diamond_users for every day in Mar. First, let create a data entry with each user comes with each day in Mar:

In [38]:
Mar = pd.date_range(start='2022-03-01', end='2022-03-31')
Dates = []
Users = []
for user_id in Diamond_users['User_id']:
    for date in Mar:
        Dates.append(date)
        Users.append(user_id)
Accumulated_points_2 = pd.DataFrame(
    {'User_id': Users,
     'DATE': Dates             
    })
Accumulated_points_2

User_id       DATE
0    43160536 2022-03-01
1    43160536 2022-03-02
2    43160536 2022-03-03
3    43160536 2022-03-04
4    43160536 2022-03-05
..        ...        ...
243  47662326 2022-03-27
244  47662326 2022-03-28
245  47662326 2022-03-29
246  47662326 2022-03-30
247  47662326 2022-03-31

[248 rows x 2 columns]

Let rows in Accumulated_points_2 pass through points_calculating function that we have defined in Question 2, Part 1

In [39]:
Accumulated_points_2['Loyalty Points'] = Accumulated_points_2.apply(lambda row: points_calculating(row['DATE'], row['User_id']), axis = 1)
Accumulated_points_2

User_id       DATE  Loyalty Points
0    43160536 2022-03-01          2202.0
1    43160536 2022-03-02          2202.0
2    43160536 2022-03-03          2202.0
3    43160536 2022-03-04          2202.0
4    43160536 2022-03-05          2202.0
..        ...        ...             ...
243  47662326 2022-03-27         22727.0
244  47662326 2022-03-28         21110.0
245  47662326 2022-03-29         21036.0
246  47662326 2022-03-30         21172.0
247  47662326 2022-03-31         20840.0

[248 rows x 3 columns]

Find Rank name Class ID of user in every day in Mar

In [40]:
Ranking_name_2 = pd.merge_asof(Accumulated_points_2.sort_values('Loyalty Points'),Ranking_rules.loc[:,['Class ID','Loyalty Points']], on = 'Loyalty Points')
Ranking_name_2

User_id       DATE  Loyalty Points  Class ID
0    44901759 2022-03-24           990.0         1
1    44901759 2022-03-30           990.0         1
2    44901759 2022-03-29           990.0         1
3    44901759 2022-03-28           990.0         1
4    44901759 2022-03-27           990.0         1
..        ...        ...             ...       ...
243  47662326 2022-03-14         28088.0         4
244  47662326 2022-03-15         28588.0         4
245  47662326 2022-03-16         29873.0         4
246  47662326 2022-03-18         29876.0         4
247  47662326 2022-03-17         30564.0         4

[248 rows x 4 columns]

Filter users in days their have Class ID = 4 (DIAMOND rank)

In [41]:
ClassID_4_users = Ranking_name_2[Ranking_name_2['Class ID']==4].sort_values('DATE')
ClassID_4_users

User_id       DATE  Loyalty Points  Class ID
157  55200938 2022-03-01          7196.0         4
221  47662326 2022-03-01         22264.0         4
104  39314846 2022-03-01          5634.0         4
118  57207697 2022-03-02          5875.0         4
145  55200938 2022-03-02          6594.0         4
..        ...        ...             ...       ...
192  57207697 2022-03-30          9847.0         4
200  57207697 2022-03-31         10926.0         4
217  47662326 2022-03-31         20840.0         4
215  50185392 2022-03-31         15545.0         4
175  51432947 2022-03-31          8307.0         4

[158 rows x 4 columns]

Let's find the users that have enough 20 days of DIAMOND in Mar

In [42]:
ClassID_4_users.groupby(ClassID_4_users['User_id'])['Class ID'].count()

User_id
39314846    19
43160536     4
44901759     7
47662326    31
50185392    22
51432947    26
55200938    19
57207697    30
Name: Class ID, dtype: int64

There were 4 users that have enough days of DIAMOND rank. Let's see if their ranks are consecutive:

In [43]:
ClassID_4_users[ClassID_4_users['User_id'] == 47662326].loc[:,'DATE']

221   2022-03-01
224   2022-03-02
226   2022-03-03
233   2022-03-04
231   2022-03-05
234   2022-03-06
235   2022-03-07
240   2022-03-08
232   2022-03-09
237   2022-03-10
236   2022-03-11
239   2022-03-12
241   2022-03-13
243   2022-03-14
244   2022-03-15
245   2022-03-16
247   2022-03-17
246   2022-03-18
242   2022-03-19
238   2022-03-20
228   2022-03-21
227   2022-03-22
230   2022-03-23
229   2022-03-24
225   2022-03-25
223   2022-03-26
222   2022-03-27
219   2022-03-28
218   2022-03-29
220   2022-03-30
217   2022-03-31
Name: DATE, dtype: datetime64[ns]

47662326 user had 31 consecutive days of DIAMOND streak

In [44]:
ClassID_4_users[ClassID_4_users['User_id'] == 50185392].loc[:,'DATE']

92    2022-03-08
97    2022-03-09
98    2022-03-12
198   2022-03-13
197   2022-03-14
199   2022-03-15
212   2022-03-16
211   2022-03-17
210   2022-03-18
209   2022-03-19
201   2022-03-20
214   2022-03-21
207   2022-03-22
208   2022-03-23
206   2022-03-24
205   2022-03-25
204   2022-03-26
203   2022-03-27
202   2022-03-28
213   2022-03-29
216   2022-03-30
215   2022-03-31
Name: DATE, dtype: datetime64[ns]

50185392 user had 20 consecutive days of DIAMOND streak

In [45]:
ClassID_4_users[ClassID_4_users['User_id'] == 51432947].loc[:,'DATE']

91    2022-03-06
102   2022-03-07
123   2022-03-08
137   2022-03-09
136   2022-03-10
135   2022-03-11
152   2022-03-12
150   2022-03-13
151   2022-03-14
144   2022-03-15
120   2022-03-16
146   2022-03-17
155   2022-03-18
162   2022-03-19
173   2022-03-20
164   2022-03-21
176   2022-03-22
177   2022-03-23
181   2022-03-24
178   2022-03-25
174   2022-03-26
179   2022-03-27
188   2022-03-28
187   2022-03-29
189   2022-03-30
175   2022-03-31
Name: DATE, dtype: datetime64[ns]

51432947 user had 26 consecutive days of DIAMOND streak

In [46]:
ClassID_4_users[ClassID_4_users['User_id'] == 57207697].loc[:,'DATE']

118   2022-03-02
119   2022-03-03
154   2022-03-04
163   2022-03-05
183   2022-03-06
184   2022-03-07
185   2022-03-08
186   2022-03-09
182   2022-03-10
168   2022-03-11
166   2022-03-12
165   2022-03-13
167   2022-03-14
170   2022-03-15
169   2022-03-16
171   2022-03-17
172   2022-03-18
161   2022-03-19
159   2022-03-20
160   2022-03-21
158   2022-03-22
180   2022-03-23
190   2022-03-24
196   2022-03-25
195   2022-03-26
194   2022-03-27
193   2022-03-28
191   2022-03-29
192   2022-03-30
200   2022-03-31
Name: DATE, dtype: datetime64[ns]

57207697 user had 30 consecutive days of DIAMOND streak.<br>
There were **4** winners of the game: **47662326, 50185392, 51432947, 57207697** and **47662326** had the special reward thanks to 31-day streak